### ISSUE TITLE
not working on Ubuntu

### ISSUE THREAD

**Issue by trappedinspacetime** [panighetti/py_sudoku#1]
Hi, 
Thank you for sharing your project. I watched the video on youtube it looks nice.
I cloned your repo and installed all the dependencies. I opened sudoku page and did the in instruction.
I got following error:

```
   python main.py
   <class 'Xlib.protocol.request.QueryExtension'>
   <class 'Xlib.protocol.request.QueryExtension'>
   Click for 'up_left'
   Click for 'down_right'
   Points taken
   Taking a screenshot
   Parsing the screenshot
   Traceback (most recent call last):
     File "main.py", line 21, in <module>
       board = utility.get_board_from_image(im)
     File "/home/**/Downloads/py_sudoku-master/utility.py", line 97, in get_board_from_image
       board.values[j][i] = cell_to_number(cell_image)
     File "/home/**/Downloads/py_sudoku-master/utility.py", line 106, in cell_to_number
       text = pytesseract.image_to_string(cell,config="-psm 6")
     File "/usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py", line 161, in image_to_string
       config=config)
     File "/usr/local/lib/python2.7/dist-packages/pytesseract/pytesseract.py", line 94, in run_tesseract
       stderr=subprocess.PIPE)
     File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
errread, errwrite)
     File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
       raise child_exception
   OSError: [Errno 2] No such file or directory
```

Do you have any idea about why it fails?

Regards.
Kenn

**Comment by panighetti** [comment]
Hi,

I'm using pytesseract to recognise the numbers. But it is just a "python wrapper for google's Tesseract-OCR". You have to install Tesseract-OCR (http://stackoverflow.com/questions/18322933/pytesser-simple-usage-error)

Linux:
`apt-get install tesseract-ocr`

Mac:
`brew install tesseract`

Tell me if it works

Thank you for your feedback

Regards.
Sandro

**Comment by trappedinspacetime** [comment]
@panighetti 
wow, it's impressive. I installed `tesseract-ocr`. After a few unsuccessful attemts it worked.
Good job, congrats!
Thank you for help.
Have a good day.
Kenn
